### ISSUE TITLE
Every day patter won't return :days correctly

### ISSUE THREAD

**Issue by roberto-robles** [VitalLabs/schedule#1]
Creating a schedule object **(schedule/->WeeklyPattern [] #{[12 0]} "PST")**

generates the following obj:
 "#schedule/weekly-pattern \"Every day at 12:00 PST\""

But reading a schedule with that pattern won't return the expected list of keywords that represents the days.
**[:monday :tuesday ... :sunday]**

**Comment by eslick** [comment]
We adjusted defaults to make this make more sense in 0.1.5
